### ISSUE TITLE
how to use the plugin in Bitbucket pipeline to generate the report? (SonarQube version: 25.2.0.102705)

### ISSUE THREAD

**Issue by JesusGarce22** [cnescatlab/sonar-cnes-report#436]
how to use the plugin in Bitbucket pipeline to generate the report?

**Comment by DooGer1** [comment]
**Using sonar-cnes-report in Bitbucket Pipelines**

To generate a report using **sonar-cnes-report** in a **Bitbucket Pipeline**, follow these steps:

### 1. Run SonarQube Analysis
Before generating a report, ensure that SonarQube analysis is performed.

```yaml
image: maven:3.8.6-openjdk-11

pipelines:
  default:
    - step:
        name: SonarQube Analysis
        services:
          - docker
        script:
          - echo "Running SonarQube scan..."
          - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
```

### 2. Install sonar-cnes-report and Generate Report
After SonarQube analysis is complete, install **sonar-cnes-report** and generate the report.

```yaml
image: node:18

pipelines:
  default:
    - step:
        name: SonarQube Analysis
        services:
          - docker
        script:
          - echo "Running SonarQube scan..."
          - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

    - step:
        name: Generate Sonar Report
        image: python:3.9
        script:
          - echo "Installing sonar-cnes-report..."
          - pip install sonar-cnes-report
          - echo "Generating report..."
          - sonar-cnes-report -s $SONAR_HOST_URL -t $SONAR_TOKEN -p my_project_key -f html,json
          - ls -l
          - echo "Uploading report as artifact..."
        artifacts:
          - cnes-report/*.html
          - cnes-report/*.json
```

### 3. Configure Environment Variables
Ensure the following environment variables are set in **Bitbucket Repository Settings** → **Repository variables**:
- `SONAR_HOST_URL` → URL of your SonarQube server (e.g., `https://sonar.mycompany.com`)
- `SONAR_TOKEN` → Authentication token for SonarQube
- `my_project_key` → SonarQube project key

### 4. Expected Outcome
- Runs SonarQube analysis
- Installs `sonar-cnes-report`
- Generates reports in **HTML** and **JSON**
- Saves the reports as artifacts in **Bitbucket Pipelines**

Now, you can download the reports from the Bitbucket Pipelines UI.

**Comment by JesusGarce22** [comment]
The pipeline show me this problem

<img width="458" alt="Image" src="https://github.com/user-attachments/assets/a95fbc31-35b2-4120-b2db-943a9758bc1f" />

**Comment by DooGer1** [comment]
Fixing "Could not find a version that satisfies the requirement sonar-cnes-report" in Bitbucket Pipelines

If your Bitbucket Pipeline shows the error:

ERROR: Could not find a version that satisfies the requirement sonar-cnes-report
ERROR: No matching distribution found for sonar-cnes-report

It means that sonar-cnes-report is not available on PyPI and needs to be manually downloaded.

🔹 Possible Causes & Solutions

1️⃣ Package is Not on PyPI

The sonar-cnes-report tool is a standalone CLI tool available on GitHub, not a Python package.

✅ Solution: Download and execute it manually:

wget https://github.com/cnescatlab/sonar-cnes-report/releases/latest/download/sonar-cnes-report.jar

Then, run the tool using:

java -jar sonar-cnes-report.jar -s $SONAR_HOST_URL -t $SONAR_TOKEN -p my_project_key -f html,json

2️⃣ Python Version Compatibility

If you still need pip install, first verify your Python version in the pipeline:

python --version

sonar-cnes-report might not support older versions.

✅ Solution: Upgrade Python in the Bitbucket pipeline:

image: python:3.9

3️⃣ Check for Private Index (Custom Repository)

If your company has a private PyPI repository, sonar-cnes-report might be hosted there.

✅ Solution: Try installing from an alternative repository:

pip install --index-url=https://your-private-repo/simple sonar-cnes-report

🔹 Final Working Bitbucket Pipeline Example

Here’s how you can correctly integrate sonar-cnes-report in Bitbucket Pipelines:

image: openjdk:11

pipelines:
  default:
    - step:
        name: SonarQube Analysis
        script:
          - echo "Running SonarQube scan..."
          - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

    - step:
        name: Generate Sonar Report
        script:
          - echo "Downloading sonar-cnes-report..."
          - wget https://github.com/cnescatlab/sonar-cnes-report/releases/latest/download/sonar-cnes-report.jar
          - echo "Generating Sonar Report..."
          - java -jar sonar-cnes-report.jar -s $SONAR_HOST_URL -t $SONAR_TOKEN -p my_project_key -f html,json
        artifacts:
          - sonar-cnes-report/*.html
          - sonar-cnes-report/*.json

✅ Key Takeaways

🚫 You can't install sonar-cnes-report via pip.

📥 Download the .jar file instead and run it using java -jar.

🛠 Ensure your pipeline has Java installed.

🔍 If needed, check for a private PyPI repository.

This should resolve your issue! 🚀 Let me know if you need further tweaks.

**Comment by JesusGarce22** [comment]
Thank you, now I got an error when performing the java - jar command.

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: fr/cnes/sonar/report/ReportCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by JesusGarce22** [comment]
I have this problem This SonarQube version is not supported by this cnesreport version.

```
SonarQube URL: https://sonarqube.xxxx-apps.net/
SonarQube online: true
Detected SonarQube version: 25.2.0.102705
[WARNING] This SonarQube version is not supported by this cnesreport version.
[WARNING] For further information, please refer to the compatibility matrix on the project GitHub page.
```

This is the pipeline step

```
    - step: &report-step
        name: Generate Sonar Report
        image: openjdk:17-slim
        script:
          - apt-get update
          - apt-get install -y wget
          - echo "Downloading sonar-cnes-report..."
          - wget -O sonar-cnes-report.jar https://github.com/cnescatlab/sonar-cnes-report/releases/download/5.0.1/sonar-cnes-report-5.0.1.jar
          - ls -l
          - java -version
          - echo "Generating Sonar Report..."
          - java -jar sonar-cnes-report.jar -s ${SONAR_HOST_URL} -t ${SONAR_TOKEN} -p ${SONAR_PROJECT_KEY} -f html,json
        artifacts:
          - sonar-cnes-report/*.html
          - sonar-cnes-report/*.json
```

**Comment by DooGer1** [comment]
**Fixing "UnsupportedClassVersionError" in Bitbucket Pipelines for Sonar CNES Report**

### **Issue**
When running `sonar-cnes-report.jar` in Bitbucket Pipelines, you may encounter the following error:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: fr/cnes/sonar/report/ReportCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

### **Cause of the Error**
- The `sonar-cnes-report.jar` file was compiled using **Java 17 (class version 61.0)**.
- Your pipeline environment is running **Java 8 (class version 52.0)**, which does not support the newer `.jar` file.

### ✅ **Solution: Upgrade Java Version in Bitbucket Pipeline**
To fix this issue, upgrade the Java version in your Bitbucket pipeline to **Java 17 or later**.

---

### **Option 1: Use an OpenJDK 17+ Image**
Modify your `.bitbucket-pipelines.yml` to use a **Java 17+ Docker image**:

```yaml
image: openjdk:17
```

or, if you need Java 21:

```yaml
image: openjdk:21
```

---

### **Option 2: Install Java 17 Manually**
If changing the base image is not an option, manually install Java 17 before running the report:

```yaml
pipelines:
  default:
    - step:
        name: Install Java 17 and Run Sonar Report
        script:
          - echo "Installing Java 17..."
          - apt-get update && apt-get install -y openjdk-17-jdk
          - java -version  # Verify Java version
          - wget https://github.com/cnescatlab/sonar-cnes-report/releases/latest/download/sonar-cnes-report.jar
          - echo "Running Sonar CNES Report..."
          - java -jar sonar-cnes-report.jar -s $SONAR_HOST_URL -t $SONAR_TOKEN -p my_project_key -f html,json
```

---

### **Verify Installed Java Version**
Before running `sonar-cnes-report.jar`, verify that Java 17+ is installed:

```bash
java -version
```

Expected output (for Java 17+):

```
openjdk version "17.0.3" 2023-04-18
OpenJDK Runtime Environment (build 17.0.3+7)
OpenJDK 64-Bit Server VM (build 17.0.3+7, mixed mode, sharing)
```

---

### 🔹 **Final Thoughts**
- 🚀 The issue occurs because `sonar-cnes-report` was compiled for **Java 17+**.
- 🔄 **Upgrade Java to at least version 17** to resolve the error.
- 🏗 **Best approach**: Use an **OpenJDK 17+ Docker image** or manually install Java 17.
